"""Migration

Revision ID: 288792c3db5a
Revises: f9c53a1d3623
Create Date: 2024-05-01 18:37:32.462629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288792c3db5a'
down_revision: Union[str, None] = 'f9c53a1d3623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Doctor_user_id_key', 'Doctor', type_='unique')
    op.drop_constraint('Patient_user_id_key', 'Patient', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Patient_user_id_key', 'Patient', ['user_id'])
    op.create_unique_constraint('Doctor_user_id_key', 'Doctor', ['user_id'])
    # ### end Alembic commands ###
