"""Migration

Revision ID: 6212e3f7087d
Revises: 9907ae8f6ba3
Create Date: 2024-05-05 15:00:55.092529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6212e3f7087d'
down_revision: Union[str, None] = '9907ae8f6ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ECGDiagram', sa.Column('ecg_date', sa.String(), nullable=True))
    op.drop_column('ECGDiagram', 'time_data')
    op.create_unique_constraint(None, 'Verify_email', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Verify_email', type_='unique')
    op.add_column('ECGDiagram', sa.Column('time_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ECGDiagram', 'ecg_date')
    # ### end Alembic commands ###
